import pytest
from unittest.mock import patch, MagicMock

@pytest.fixture
async def setup_auth(client):
    res = await client.post(
        "/api/auth/register",
        json={"email": "agent@test.com", "password": "pass", "name": "Agent User", "team_name": "Agent Team"}
    )
    data = res.json()
    return {"Authorization": f"Bearer {data['access_token']}"}

@pytest.mark.asyncio
async def test_generate_journey_agentic_loop(client, setup_auth):
    """Test the AI agent loop by mocking the LLM response."""
    
    # We provide a valid JSON structure that matches the LLMJourney schema
    valid_json = '''
    {
      "name": "Test LLM Journey",
      "description": "Generated by AI",
      "stages": [
        {
          "name": "Stage 1",
          "description": "Desc 1",
          "goals": [{"text": "G1"}],
          "touchpoints": [{"text": "T1"}],
          "content": [{"text": "C1", "content_type": "email"}]
        },
        {
          "name": "Stage 2",
          "description": "Desc 2",
          "goals": [{"text": "G2"}],
          "touchpoints": [{"text": "T2"}],
          "content": [{"text": "C2", "content_type": "email"}]
        },
        {
          "name": "Stage 3",
          "description": "Desc 3",
          "goals": [{"text": "G3"}],
          "touchpoints": [{"text": "T3"}],
          "content": [{"text": "C3", "content_type": "email"}]
        },
        {
          "name": "Stage 4",
          "description": "Desc 4",
          "goals": [{"text": "G4"}],
          "touchpoints": [{"text": "T4"}],
          "content": [{"text": "C4", "content_type": "email"}]
        }
      ]
    }
    '''
    
    # Mock the generate_content call from google.generativeai and local _generate_ollama from AgentService
    with patch("google.generativeai.GenerativeModel.generate_content") as mock_generate, \
         patch("app.services.agent_service.AgentService._generate_ollama") as mock_ollama:
        mock_response = MagicMock()
        mock_response.text = valid_json
        mock_generate.return_value = mock_response
        mock_ollama.return_value = valid_json
        
        response = await client.post(
            "/api/ai/generate-journey",
            json={"prompt": "Make an onboarding journey"},
            headers=setup_auth
        )
        
        # The agent should validate the JSON, save it to the DB, and return the Journey
        assert response.status_code == 200
        data = response.json()
        
        assert data["name"] == "Test LLM Journey"
        assert len(data["stages"]) == 4
        
        first_stage = data["stages"][0]
        assert first_stage["name"] == "Stage 1"
        assert len(first_stage["goals"]) == 1
        assert first_stage["goals"][0]["text"] == "G1"
