"""Add leads table

Revision ID: 7e524bc56427
Revises: None
Create Date: 2026-07-01 21:29:28.557200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e524bc56427'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('journey_id', sa.String(length=36), nullable=False),
    sa.Column('stage_id', sa.String(length=36), nullable=True),
    sa.Column('persona_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_journey_id'), 'leads', ['journey_id'], unique=False)
    op.create_index(op.f('ix_leads_persona_id'), 'leads', ['persona_id'], unique=False)
    op.create_index(op.f('ix_leads_stage_id'), 'leads', ['stage_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_stage_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_persona_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_journey_id'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
